# Generated by Django 4.2.4 on 2023-08-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_email_confirmed_user_email_verify_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('github', 'GitHub')], default='email', max_length=50),
        ),
    ]
